spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.200.231:3306/blockchain_manager?autoReconnect=true&useUnicode=true
    password: Hhl@1234
    username: haly