spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/blockchain_manager?autoReconnect=true&useUnicode=true
    username: debian-sys-maint
    password: ${MYSQL_PASS}
server:
  port: 8080